server:
  port: 8083
thread:
  pool:
    corePoolSize: 50
    maxPoolSize: 500
    keepAliveSeconds: 10000
    queueCapacity: 1000
config:
  server:
    zk: 127.0.0.1:2181
    project: /ashe/provider1
    version: 1.0
    group: dev